package net.divinerpg.dimensions.arcana;

import com.gamerforea.divinerpg.EventConfig;
import com.gamerforea.eventhelper.util.EventUtils;
import net.divinerpg.utils.blocks.ArcanaBlocks;
import net.divinerpg.utils.config.ConfigurationHelper;
import net.divinerpg.utils.events.ArcanaPortalCoords;
import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.util.MathHelper;
import net.minecraft.world.Teleporter;
import net.minecraft.world.World;
import net.minecraft.world.WorldServer;

// TODO gamerforEA use TeleporterArcana.setBlock(...)
public class TeleporterArcana extends Teleporter
{
	protected WorldServer myWorld;

	public TeleporterArcana(WorldServer var1)
	{
		super(var1);
		this.myWorld = var1;
	}

	@Override
	public boolean placeInExistingPortal(Entity entity, double notUsed_entityX, double notUsed_entityY, double notUsed_entityZ, float notUsed_entityRotation)
	{
		ArcanaPortalCoords props = ArcanaPortalCoords.getProperties((EntityPlayer) entity);
		if (entity.dimension == ConfigurationHelper.arcana)
		{
			int chunkX = MathHelper.floor_double(entity.posX) & ~0xf;
			int chunkZ = MathHelper.floor_double(entity.posZ) & ~0xf;
			int y;

			props.setReturnPortalX(entity.posX);
			props.setReturnPortalY(entity.posY);
			props.setReturnPortalZ(entity.posZ);

			// Find existing portal
			for (y = 9; y < 40; y += 8)
			{
				if (this.myWorld.getBlock(chunkX + 7, y, chunkZ + 7) == ArcanaBlocks.arcanaPortal)
				{
					entity.setLocationAndAngles(chunkX + 7.5D, y + 0.5D, chunkZ + 7.5D, entity.rotationYaw, 0.0F);
					entity.motionX = entity.motionY = entity.motionZ = 0.0D;
					return true;
				}
			}

			// Find a location to create a new portal room, avoiding double high rooms
			for (y = 8; y < 40; y += 8)
			{
				if (this.myWorld.getBlock(chunkX + 7, y, chunkZ + 7) != Blocks.air && this.myWorld.getBlock(chunkX + 7, y + 8, chunkZ + 7) != Blocks.air)
				{
					this.generatePortalRoom(this.myWorld, chunkX, y, chunkZ);
					entity.setLocationAndAngles(chunkX + 7.5D, y + 1.5D, chunkZ + 7.5D, entity.rotationYaw, 0.0F);
					entity.motionX = entity.motionY = entity.motionZ = 0.0D;
					return true;
				}
			}
		}
		else
		{
			entity.setLocationAndAngles(props.getReturnPortalX(), props.getReturnPortalY(), props.getReturnPortalZ(), entity.rotationYaw, 0.0F);
			entity.motionX = entity.motionY = entity.motionZ = 0.0D;
			return true;
		}

		return false;
	}

	private void generatePortalRoom(World world, int x, int y, int z)
	{

		Block arcanaPortal = ArcanaBlocks.arcanaPortal;
		Block arcanaHardPortalFrame = ArcanaBlocks.arcanaHardPortalFrame;
		Block dungeonBricks = ArcanaBlocks.degradedBrick;
		Block ancientbricks = ArcanaBlocks.ancientBrick;
		Block ancientTile = ArcanaBlocks.ancientTile;
		Block arcanaPower = ArcanaBlocks.arcaniumPower;

		for (int n = 0; n < 16; n++)
		{
			for (int m = 0; m < 16; m++)
			{
				for (int o = 1; o < 8; o++)
				{
					setBlock(world, x + n, y + o, z + m, Blocks.air);
				}
			}
		}

		setBlock(world, x + 0, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 1, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 2, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 3, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 4, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 5, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 10, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 11, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 12, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 13, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 14, ancientbricks);
		setBlock(world, x + 0, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 0, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 1, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 2, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 3, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 4, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 5, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 6, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 9, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 10, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 11, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 12, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 13, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 14, dungeonBricks);
		setBlock(world, x + 0, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 0, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 1, ancientTile);
		setBlock(world, x + 0, y + 2, z + 2, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 3, ancientTile);
		setBlock(world, x + 0, y + 2, z + 4, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 5, ancientTile);
		setBlock(world, x + 0, y + 2, z + 6, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 9, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 10, ancientTile);
		setBlock(world, x + 0, y + 2, z + 11, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 12, ancientTile);
		setBlock(world, x + 0, y + 2, z + 13, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 14, dungeonBricks);
		setBlock(world, x + 0, y + 2, z + 15, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 1, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 2, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 3, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 4, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 5, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 6, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 7, arcanaPower);
		setBlock(world, x + 0, y + 3, z + 8, arcanaPower);
		setBlock(world, x + 0, y + 3, z + 9, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 10, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 11, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 12, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 13, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 14, dungeonBricks);
		setBlock(world, x + 0, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 0, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 1, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 2, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 3, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 4, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 5, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 6, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 7, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 8, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 9, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 10, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 11, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 12, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 13, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 14, ancientbricks);
		setBlock(world, x + 0, y + 4, z + 15, dungeonBricks);
		setBlock(world, x + 0, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 0, y + 5, z + 1, ancientTile);
		setBlock(world, x + 0, y + 5, z + 2, ancientbricks);
		setBlock(world, x + 0, y + 5, z + 3, ancientTile);
		setBlock(world, x + 0, y + 5, z + 4, ancientbricks);
		setBlock(world, x + 0, y + 5, z + 5, ancientTile);
		setBlock(world, x + 0, y + 5, z + 6, ancientbricks);
		setBlock(world, x + 0, y + 5, z + 7, ancientTile);
		setBlock(world, x + 0, y + 5, z + 8, ancientbricks);
		setBlock(world, x + 0, y + 5, z + 9, ancientTile);
		setBlock(world, x + 0, y + 5, z + 10, ancientbricks);
		setBlock(world, x + 0, y + 5, z + 11, ancientTile);
		setBlock(world, x + 0, y + 5, z + 12, ancientbricks);
		setBlock(world, x + 0, y + 5, z + 13, ancientTile);
		setBlock(world, x + 0, y + 5, z + 14, ancientbricks);
		setBlock(world, x + 0, y + 5, z + 15, dungeonBricks);
		setBlock(world, x + 0, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 1, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 2, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 3, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 4, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 5, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 6, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 7, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 8, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 9, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 10, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 11, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 12, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 13, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 14, ancientbricks);
		setBlock(world, x + 0, y + 6, z + 15, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 1, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 2, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 3, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 4, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 5, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 6, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 7, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 8, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 9, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 10, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 11, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 12, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 13, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 14, dungeonBricks);
		setBlock(world, x + 0, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 1, y + 0, z + 1, ArcanaBlocks.dungenLamp);
		setBlock(world, x + 1, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 5, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 6, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 1, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 1, y + 0, z + 9, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 10, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 1, y + 0, z + 14, ArcanaBlocks.dungenLamp);
		setBlock(world, x + 1, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 1, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 1, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 1, y + 2, z + 0, ancientTile);
		setBlock(world, x + 1, y + 2, z + 15, ancientTile);
		setBlock(world, x + 1, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 1, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 1, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 1, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 1, y + 5, z + 0, ancientTile);
		setBlock(world, x + 1, y + 5, z + 15, ancientbricks);
		setBlock(world, x + 1, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 1, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 1, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 1, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 2, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 5, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 6, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 2, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 2, y + 0, z + 9, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 10, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 2, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 2, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 2, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 2, y + 2, z + 0, dungeonBricks);
		setBlock(world, x + 2, y + 2, z + 15, dungeonBricks);
		setBlock(world, x + 2, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 2, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 2, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 2, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 2, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 2, y + 5, z + 15, ancientTile);
		setBlock(world, x + 2, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 2, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 2, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 2, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 3, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 5, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 6, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 3, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 3, y + 0, z + 9, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 10, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 3, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 3, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 3, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 3, y + 2, z + 0, ancientTile);
		setBlock(world, x + 3, y + 2, z + 15, ancientTile);
		setBlock(world, x + 3, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 3, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 3, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 3, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 3, y + 5, z + 0, ancientTile);
		setBlock(world, x + 3, y + 5, z + 15, ancientbricks);
		setBlock(world, x + 3, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 3, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 3, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 3, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 4, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 5, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 4, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 4, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 4, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 4, y + 0, z + 10, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 4, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 4, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 4, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 4, y + 2, z + 0, dungeonBricks);
		setBlock(world, x + 4, y + 2, z + 15, dungeonBricks);
		setBlock(world, x + 4, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 4, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 4, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 4, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 4, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 4, y + 5, z + 15, ancientTile);
		setBlock(world, x + 4, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 4, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 4, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 4, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 5, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 5, ancientbricks);
		setBlock(world, x + 5, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 5, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 5, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 5, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 5, y + 0, z + 10, ancientbricks);
		setBlock(world, x + 5, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 5, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 5, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 5, y + 1, z + 6, arcanaHardPortalFrame);
		setBlock(world, x + 5, y + 1, z + 7, arcanaHardPortalFrame);
		setBlock(world, x + 5, y + 1, z + 8, arcanaHardPortalFrame);
		setBlock(world, x + 5, y + 1, z + 9, arcanaHardPortalFrame);
		setBlock(world, x + 5, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 5, y + 2, z + 0, ancientTile);
		setBlock(world, x + 5, y + 2, z + 15, ancientTile);
		setBlock(world, x + 5, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 5, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 5, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 5, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 5, y + 5, z + 0, ancientTile);
		setBlock(world, x + 5, y + 5, z + 15, ancientbricks);
		setBlock(world, x + 5, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 5, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 5, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 5, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 6, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 6, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 6, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 6, y + 0, z + 4, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 5, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 10, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 11, ancientbricks);
		setBlock(world, x + 6, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 6, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 6, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 6, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 6, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 6, y + 1, z + 5, arcanaHardPortalFrame);
		setBlock(world, x + 6, y + 1, z + 6, arcanaPortal);
		setBlock(world, x + 6, y + 1, z + 7, arcanaPortal);
		setBlock(world, x + 6, y + 1, z + 8, arcanaPortal);
		setBlock(world, x + 6, y + 1, z + 9, arcanaPortal);
		setBlock(world, x + 6, y + 1, z + 10, arcanaHardPortalFrame);
		setBlock(world, x + 6, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 6, y + 2, z + 0, dungeonBricks);
		setBlock(world, x + 6, y + 2, z + 15, dungeonBricks);
		setBlock(world, x + 6, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 6, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 6, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 6, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 6, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 6, y + 5, z + 15, ancientTile);
		setBlock(world, x + 6, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 6, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 6, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 6, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 7, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 1, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 2, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 3, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 4, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 5, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 10, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 11, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 12, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 13, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 14, ancientbricks);
		setBlock(world, x + 7, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 7, y + 1, z + 5, arcanaHardPortalFrame);
		setBlock(world, x + 7, y + 1, z + 6, arcanaPortal);
		setBlock(world, x + 7, y + 1, z + 7, arcanaPortal);
		setBlock(world, x + 7, y + 1, z + 8, arcanaPortal);
		setBlock(world, x + 7, y + 1, z + 9, arcanaPortal);
		setBlock(world, x + 7, y + 1, z + 10, arcanaHardPortalFrame);
		setBlock(world, x + 7, y + 3, z + 0, arcanaPower);
		setBlock(world, x + 7, y + 3, z + 15, arcanaPower);
		setBlock(world, x + 7, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 7, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 7, y + 5, z + 0, ancientTile);
		setBlock(world, x + 7, y + 5, z + 15, ancientbricks);
		setBlock(world, x + 7, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 7, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 7, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 7, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 8, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 1, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 2, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 3, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 4, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 5, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 10, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 11, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 12, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 13, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 14, ancientbricks);
		setBlock(world, x + 8, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 8, y + 1, z + 5, arcanaHardPortalFrame);
		setBlock(world, x + 8, y + 1, z + 6, arcanaPortal);
		setBlock(world, x + 8, y + 1, z + 7, arcanaPortal);
		setBlock(world, x + 8, y + 1, z + 8, arcanaPortal);
		setBlock(world, x + 8, y + 1, z + 9, arcanaPortal);
		setBlock(world, x + 8, y + 1, z + 10, arcanaHardPortalFrame);
		setBlock(world, x + 8, y + 3, z + 0, arcanaPower);
		setBlock(world, x + 8, y + 3, z + 15, arcanaPower);
		setBlock(world, x + 8, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 8, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 8, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 8, y + 5, z + 15, ancientTile);
		setBlock(world, x + 8, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 8, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 8, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 8, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 9, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 9, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 9, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 9, y + 0, z + 4, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 5, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 10, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 11, ancientbricks);
		setBlock(world, x + 9, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 9, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 9, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 9, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 9, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 9, y + 1, z + 5, arcanaHardPortalFrame);
		setBlock(world, x + 9, y + 1, z + 6, arcanaPortal);
		setBlock(world, x + 9, y + 1, z + 7, arcanaPortal);
		setBlock(world, x + 9, y + 1, z + 8, arcanaPortal);
		setBlock(world, x + 9, y + 1, z + 9, arcanaPortal);
		setBlock(world, x + 9, y + 1, z + 10, arcanaHardPortalFrame);
		setBlock(world, x + 9, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 9, y + 2, z + 0, dungeonBricks);
		setBlock(world, x + 9, y + 2, z + 15, dungeonBricks);
		setBlock(world, x + 9, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 9, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 9, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 9, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 9, y + 5, z + 0, ancientTile);
		setBlock(world, x + 9, y + 5, z + 15, ancientbricks);
		setBlock(world, x + 9, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 9, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 9, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 9, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 10, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 5, ancientbricks);
		setBlock(world, x + 10, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 10, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 10, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 10, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 10, y + 0, z + 10, ancientbricks);
		setBlock(world, x + 10, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 10, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 10, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 10, y + 1, z + 6, arcanaHardPortalFrame);
		setBlock(world, x + 10, y + 1, z + 7, arcanaHardPortalFrame);
		setBlock(world, x + 10, y + 1, z + 8, arcanaHardPortalFrame);
		setBlock(world, x + 10, y + 1, z + 9, arcanaHardPortalFrame);
		setBlock(world, x + 10, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 10, y + 2, z + 0, ancientTile);
		setBlock(world, x + 10, y + 2, z + 15, ancientTile);
		setBlock(world, x + 10, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 10, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 10, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 10, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 10, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 10, y + 5, z + 15, ancientTile);
		setBlock(world, x + 10, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 10, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 10, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 10, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 11, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 5, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 11, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 11, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 11, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 11, y + 0, z + 10, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 11, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 11, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 11, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 11, y + 2, z + 0, dungeonBricks);
		setBlock(world, x + 11, y + 2, z + 15, dungeonBricks);
		setBlock(world, x + 11, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 11, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 11, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 11, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 11, y + 5, z + 0, ancientTile);
		setBlock(world, x + 11, y + 5, z + 15, ancientbricks);
		setBlock(world, x + 11, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 11, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 11, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 11, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 12, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 5, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 6, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 12, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 12, y + 0, z + 9, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 10, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 12, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 12, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 12, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 12, y + 2, z + 0, ancientTile);
		setBlock(world, x + 12, y + 2, z + 15, ancientTile);
		setBlock(world, x + 12, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 12, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 12, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 12, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 12, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 12, y + 5, z + 15, ancientTile);
		setBlock(world, x + 12, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 12, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 12, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 12, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 13, y + 0, z + 1, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 5, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 6, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 13, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 13, y + 0, z + 9, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 10, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 13, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 13, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 13, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 13, y + 2, z + 0, dungeonBricks);
		setBlock(world, x + 13, y + 2, z + 15, dungeonBricks);
		setBlock(world, x + 13, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 13, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 13, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 13, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 13, y + 5, z + 0, ancientTile);
		setBlock(world, x + 13, y + 5, z + 15, ancientbricks);
		setBlock(world, x + 13, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 13, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 13, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 13, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 14, y + 0, z + 1, ArcanaBlocks.dungenLamp);
		setBlock(world, x + 14, y + 0, z + 2, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 3, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 4, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 5, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 6, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 14, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 14, y + 0, z + 9, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 10, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 11, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 12, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 13, dungeonBricks);
		setBlock(world, x + 14, y + 0, z + 14, ArcanaBlocks.dungenLamp);
		setBlock(world, x + 14, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 14, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 14, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 14, y + 2, z + 0, ancientTile);
		setBlock(world, x + 14, y + 2, z + 15, ancientTile);
		setBlock(world, x + 14, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 14, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 14, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 14, y + 4, z + 15, ancientbricks);
		setBlock(world, x + 14, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 14, y + 5, z + 15, ancientTile);
		setBlock(world, x + 14, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 14, y + 6, z + 15, ancientbricks);
		setBlock(world, x + 14, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 14, y + 7, z + 15, dungeonBricks);
		setBlock(world, x + 15, y + 0, z + 0, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 1, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 2, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 3, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 4, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 5, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 6, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 7, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 8, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 9, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 10, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 11, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 12, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 13, ancientbricks);
		setBlock(world, x + 15, y + 0, z + 14, dungeonBricks);
		setBlock(world, x + 15, y + 0, z + 15, ancientbricks);
		setBlock(world, x + 15, y + 1, z + 0, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 1, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 2, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 3, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 4, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 5, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 6, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 9, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 10, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 11, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 12, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 13, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 14, dungeonBricks);
		setBlock(world, x + 15, y + 1, z + 15, dungeonBricks);
		setBlock(world, x + 15, y + 2, z + 0, dungeonBricks);
		setBlock(world, x + 15, y + 2, z + 1, ancientTile);
		setBlock(world, x + 15, y + 2, z + 2, dungeonBricks);
		setBlock(world, x + 15, y + 2, z + 3, ancientTile);
		setBlock(world, x + 15, y + 2, z + 4, dungeonBricks);
		setBlock(world, x + 15, y + 2, z + 5, ancientTile);
		setBlock(world, x + 15, y + 2, z + 6, dungeonBricks);
		setBlock(world, x + 15, y + 2, z + 9, dungeonBricks);
		setBlock(world, x + 15, y + 2, z + 10, ancientTile);
		setBlock(world, x + 15, y + 2, z + 11, dungeonBricks);
		setBlock(world, x + 15, y + 2, z + 12, ancientTile);
		setBlock(world, x + 15, y + 2, z + 13, dungeonBricks);
		setBlock(world, x + 15, y + 2, z + 14, ancientTile);
		setBlock(world, x + 15, y + 2, z + 15, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 0, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 1, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 2, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 3, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 4, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 5, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 6, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 7, arcanaPower);
		setBlock(world, x + 15, y + 3, z + 8, arcanaPower);
		setBlock(world, x + 15, y + 3, z + 9, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 10, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 11, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 12, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 13, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 14, dungeonBricks);
		setBlock(world, x + 15, y + 3, z + 15, dungeonBricks);
		setBlock(world, x + 15, y + 4, z + 0, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 1, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 2, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 3, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 4, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 5, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 6, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 7, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 8, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 9, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 10, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 11, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 12, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 13, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 14, ancientbricks);
		setBlock(world, x + 15, y + 4, z + 15, dungeonBricks);
		setBlock(world, x + 15, y + 5, z + 0, ancientbricks);
		setBlock(world, x + 15, y + 5, z + 1, ancientTile);
		setBlock(world, x + 15, y + 5, z + 2, ancientbricks);
		setBlock(world, x + 15, y + 5, z + 3, ancientTile);
		setBlock(world, x + 15, y + 5, z + 4, ancientbricks);
		setBlock(world, x + 15, y + 5, z + 5, ancientTile);
		setBlock(world, x + 15, y + 5, z + 6, ancientbricks);
		setBlock(world, x + 15, y + 5, z + 7, ancientTile);
		setBlock(world, x + 15, y + 5, z + 8, ancientbricks);
		setBlock(world, x + 15, y + 5, z + 9, ancientTile);
		setBlock(world, x + 15, y + 5, z + 10, ancientbricks);
		setBlock(world, x + 15, y + 5, z + 11, ancientTile);
		setBlock(world, x + 15, y + 5, z + 12, ancientbricks);
		setBlock(world, x + 15, y + 5, z + 13, ancientTile);
		setBlock(world, x + 15, y + 5, z + 14, ancientbricks);
		setBlock(world, x + 15, y + 5, z + 15, dungeonBricks);
		setBlock(world, x + 15, y + 6, z + 0, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 1, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 2, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 3, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 4, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 5, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 6, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 7, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 8, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 9, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 10, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 11, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 12, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 13, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 14, ancientbricks);
		setBlock(world, x + 15, y + 6, z + 15, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 0, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 1, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 2, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 3, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 4, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 5, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 6, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 7, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 8, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 9, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 10, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 11, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 12, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 13, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 14, dungeonBricks);
		setBlock(world, x + 15, y + 7, z + 15, dungeonBricks);
	}

	@Override
	public boolean makePortal(Entity entity)
	{
		return false;
	}

	// TODO gamerforEA code start
	private static final boolean setBlock(World world, int x, int y, int z, Block block)
	{
		if (!EventConfig.portalGeneration)
			return false;
		if (EventConfig.teleportGenPrivateCheck && EventUtils.isInPrivate(world, x, y, z))
			return false;

		if (EventConfig.portalStoneFrame && (block == ArcanaBlocks.arcanaHardPortalFrame || block == ArcanaBlocks.arcanaPortalFrame))
			block = Blocks.stone;

		return world.setBlock(x, y, z, block);
	}
	// TODO gamerforEA code end
}
